DROP TABLE IF EXISTS `user` CASCADE;
CREATE TABLE `user`
(
	`id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`username` VARCHAR(255) NOT NULL
);
